package org.unified.common.enums;

/**
 * Enum representing supported export formats for reports.
 * These formats determine the type of output generated by the reporting engine.
 */
public enum FileExportFormat {

    /**
     * Export the report as a PDF document.
     */
    PDF,

    /**
     * Export the report as an HTML page.
     */
    HTML,

    /**
     * Export the report as an Excel spreadsheet (.xlsx).
     */
    XLSX,

    /**
     * Export the report as an XML file.
     */
    XML,

    /**
     * Export the report as a Word document (.docx).
     */
    DOCX,

    /**
     * Export the report as a CSV (Comma-Separated Values) file.
     */
    CSV
}
